
create table mesorregiao
(
    idmesorregiao integer,
    nome character varying(50) not null,
    idestado integer not null,
    primary key (idmesorregiao)
);

insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1101, 'Madeira-Guaporé', 11);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1102, 'Leste Rondoniense', 11);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1201, 'Vale do Juruá', 12);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1202, 'Vale do Acre', 12);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1301, 'Norte Amazonense', 13);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1302, 'Sudoeste Amazonense', 13);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1303, 'Centro Amazonense', 13);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1304, 'Sul Amazonense', 13);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1401, 'Norte de Roraima', 14);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1402, 'Sul de Roraima', 14);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1501, 'Baixo Amazonas', 15);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1502, 'Marajó', 15);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1503, 'Metropolitana de Belém', 15);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1504, 'Nordeste Paraense', 15);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1505, 'Sudoeste Paraense', 15);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1506, 'Sudeste Paraense', 15);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1601, 'Norte do Amapá', 16);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1602, 'Sul do Amapá', 16);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1701, 'Ocidental do Tocantins', 17);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 1702, 'Oriental do Tocantins', 17);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2101, 'Norte Maranhense', 21);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2102, 'Oeste Maranhense', 21);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2103, 'Centro Maranhense', 21);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2104, 'Leste Maranhense', 21);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2105, 'Sul Maranhense', 21);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2201, 'Norte Piauiense', 22);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2202, 'Centro-Norte Piauiense', 22);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2203, 'Sudoeste Piauiense', 22);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2204, 'Sudeste Piauiense', 22);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2301, 'Noroeste Cearense', 23);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2302, 'Norte Cearense', 23);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2303, 'Metropolitana de Fortaleza', 23);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2304, 'Sertões Cearenses', 23);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2305, 'Jaguaribe', 23);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2306, 'Centro-Sul Cearense', 23);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2307, 'Sul Cearense', 23);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2401, 'Oeste Potiguar', 24);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2402, 'Central Potiguar', 24);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2403, 'Agreste Potiguar', 24);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2404, 'Leste Potiguar', 24);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2501, 'Sertão Paraibano', 25);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2502, 'Borborema', 25);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2503, 'Agreste Paraibano', 25);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2504, 'Mata Paraibana', 25);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2601, 'Sertão Pernambucano', 26);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2602, 'São Francisco Pernambucano', 26);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2603, 'Agreste Pernambucano', 26);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2604, 'Mata Pernambucana', 26);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2605, 'Metropolitana de Recife', 26);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2701, 'Sertão Alagoano', 27);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2702, 'Agreste Alagoano', 27);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2703, 'Leste Alagoano', 27);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2801, 'Sertão Sergipano', 28);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2802, 'Agreste Sergipano', 28);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2803, 'Leste Sergipano', 28);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2901, 'Extremo Oeste Baiano', 29);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2902, 'Vale São-Franciscano da Bahia', 29);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2903, 'Centro Norte Baiano', 29);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2904, 'Nordeste Baiano', 29);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2905, 'Metropolitana de Salvador', 29);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2906, 'Centro Sul Baiano', 29);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 2907, 'Sul Baiano', 29);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3101, 'Noroeste de Minas', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3102, 'Norte de Minas', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3103, 'Jequitinhonha', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3104, 'Vale do Mucuri', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3105, 'Triângulo Mineiro/Alto Paranaíba', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3106, 'Central Mineira', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3107, 'Metropolitana de Belo Horizonte', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3108, 'Vale do Rio Doce', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3109, 'Oeste de Minas', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3110, 'Sul/Sudoeste de Minas', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3111, 'Campo das Vertentes', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3112, 'Zona da Mata', 31);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3201, 'Noroeste Espírito-santense', 32);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3202, 'Litoral Norte Espírito-santense', 32);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3203, 'Central Espírito-santense', 32);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3204, 'Sul Espírito-santense', 32);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3301, 'Noroeste Fluminense', 33);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3302, 'Norte Fluminense', 33);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3303, 'Centro Fluminense', 33);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3304, 'Baixadas', 33);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3305, 'Sul Fluminense', 33);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3306, 'Metropolitana do Rio de Janeiro', 33);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3501, 'São José do Rio Preto', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3502, 'Ribeirão Preto', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3503, 'Araçatuba', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3504, 'Bauru', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3505, 'Araraquara', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3506, 'Piracicaba', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3507, 'Campinas', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3508, 'Presidente Prudente', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3509, 'Marília', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3510, 'Assis', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3511, 'Itapetininga', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3512, 'Macro Metropolitana Paulista', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3513, 'Vale do Paraíba Paulista', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3514, 'Litoral Sul Paulista', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 3515, 'Metropolitana de São Paulo', 35);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4101, 'Noroeste Paranaense', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4102, 'Centro Ocidental Paranaense', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4103, 'Norte Central Paranaense', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4104, 'Norte Pioneiro Paranaense', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4105, 'Centro Oriental Paranaense', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4106, 'Oeste Paranaense', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4107, 'Sudoeste Paranaense', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4108, 'Centro-Sul Paranaense', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4109, 'Sudeste Paranaense', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4110, 'Metropolitana de Curitiba', 41);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4201, 'Oeste Catarinense', 42);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4202, 'Norte Catarinense', 42);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4203, 'Serrana', 42);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4204, 'Vale do Itajaí', 42);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4205, 'Grande Florianópolis', 42);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4206, 'Sul Catarinense', 42);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4301, 'Noroeste Rio-grandense', 43);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4302, 'Nordeste Rio-grandense', 43);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4303, 'Centro Ocidental Rio-grandense', 43);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4304, 'Centro Oriental Rio-grandense', 43);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4305, 'Metropolitana de Porto Alegre', 43);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4306, 'Sudoeste Rio-grandense', 43);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 4307, 'Sudeste Rio-grandense', 43);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5001, 'Pantanais Sul Mato-grossense', 50);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5002, 'Centro Norte de Mato Grosso do Sul', 50);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5003, 'Leste de Mato Grosso do Sul', 50);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5004, 'Sudoeste de Mato Grosso do Sul', 50);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5101, 'Norte Mato-grossense', 51);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5102, 'Nordeste Mato-grossense', 51);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5103, 'Sudoeste Mato-grossense', 51);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5104, 'Centro-Sul Mato-grossense', 51);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5105, 'Sudeste Mato-grossense', 51);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5201, 'Noroeste Goiano', 52);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5202, 'Norte Goiano', 52);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5203, 'Centro Goiano', 52);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5204, 'Leste Goiano', 52);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5205, 'Sul Goiano', 52);
insert into mesorregiao (idmesorregiao, nome, idestado) values ( 5301, 'Distrito Federal', 53);
