
create table microrregiao
(
    idmicrorregiao integer,
    nome character varying(50) not null,
    idmesorregiao integer not null,
    primary key (idmicrorregiao) 
);

insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 11001, 'Porto Velho', 1101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 11002, 'Guajará-Mirim', 1101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 11003, 'Ariquemes', 1102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 11004, 'Ji-Paraná', 1102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 11005, 'Alvorada D\"Oeste', 1102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 11006, 'Cacoal', 1102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 11007, 'Vilhena', 1102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 11008, 'Colorado do Oeste', 1102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 12001, 'Cruzeiro do Sul', 1201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 12002, 'Tarauacá', 1201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 12003, 'Sena Madureira', 1202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 12004, 'Rio Branco', 1202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 12005, 'Brasiléia', 1202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13001, 'Rio Negro', 1301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13002, 'Japurá', 1301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13003, 'Alto Solimões', 1302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13004, 'Juruá', 1302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13005, 'Tefé', 1303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13006, 'Coari', 1303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13007, 'Manaus', 1303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13008, 'Rio Preto da Eva', 1303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13009, 'Itacoatiara', 1303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13010, 'Parintins', 1303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13011, 'Boca do Acre', 1304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13012, 'Purus', 1304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 13013, 'Madeira', 1304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 14001, 'Boa Vista', 1401);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 14002, 'Nordeste de Roraima', 1401);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 14003, 'Caracaraí', 1402);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 14004, 'Sudeste de Roraima', 1402);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15001, 'Óbidos', 1501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15002, 'Santarém', 1501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15003, 'Almeirim', 1501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15004, 'Portel', 1502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15005, 'Furos de Breves', 1502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15006, 'Arari', 1502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15007, 'Belém', 1503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15008, 'Castanhal', 1503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15009, 'Salgado', 1504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15010, 'Bragantina', 1504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15011, 'Cametá', 1504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15012, 'Tomé-Açu', 1504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15013, 'Guamá', 1504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15014, 'Itaituba', 1505);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15015, 'Altamira', 1505);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15016, 'Tucuruí', 1506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15017, 'Paragominas', 1506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15018, 'São Félix do Xingu', 1506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15019, 'Parauapebas', 1506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15020, 'Marabá', 1506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15021, 'Redenção', 1506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 15022, 'Conceição do Araguaia', 1506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 16001, 'Oiapoque', 1601);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 16002, 'Amapá', 1601);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 16003, 'Macapá', 1602);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 16004, 'Mazagão', 1602);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 17001, 'Bico do Papagaio', 1701);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 17002, 'Araguaína', 1701);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 17003, 'Miracema do Tocantins', 1701);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 17004, 'Rio Formoso', 1701);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 17005, 'Gurupi', 1701);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 17006, 'Porto Nacional', 1702);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 17007, 'Jalapão', 1702);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 17008, 'Dianópolis', 1702);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21001, 'Litoral Ocidental Maranhense', 2101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21002, 'Aglomeração Urbana de São Luís', 2101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21003, 'Rosário', 2101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21004, 'Lençóis Maranhenses', 2101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21005, 'Baixada Maranhense', 2101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21006, 'Itapecuru Mirim', 2101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21007, 'Gurupi', 2102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21008, 'Pindaré', 2102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21009, 'Imperatriz', 2102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21010, 'Médio Mearim', 2103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21011, 'Alto Mearim e Grajaú', 2103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21012, 'Presidente Dutra', 2103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21013, 'Baixo Parnaíba Maranhense', 2104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21014, 'Chapadinha', 2104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21015, 'Codó', 2104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21016, 'Coelho Neto', 2104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21017, 'Caxias', 2104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21018, 'Chapadas do Alto Itapecuru', 2104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21019, 'Porto Franco', 2105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21020, 'Gerais de Balsas', 2105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 21021, 'Chapadas das Mangabeiras', 2105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22001, 'Baixo Parnaíba Piauiense', 2201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22002, 'Litoral Piauiense', 2201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22003, 'Teresina', 2202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22004, 'Campo Maior', 2202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22005, 'Médio Parnaíba Piauiense', 2202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22006, 'Valença do Piauí', 2202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22007, 'Alto Parnaíba Piauiense', 2203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22008, 'Bertolínia', 2203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22009, 'Floriano', 2203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22010, 'Alto Médio Gurguéia', 2203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22011, 'São Raimundo Nonato', 2203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22012, 'Chapadas do Extremo Sul Piauiense', 2203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22013, 'Picos', 2204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22014, 'Pio IX', 2204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 22015, 'Alto Médio Canindé', 2204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23001, 'Litoral de Camocim e Acaraú', 2301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23002, 'Ibiapaba', 2301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23003, 'Coreaú', 2301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23004, 'Meruoca', 2301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23005, 'Sobral', 2301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23006, 'Ipu', 2301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23007, 'Santa Quitéria', 2301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23008, 'Itapipoca', 2302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23009, 'Baixo Curu', 2302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23010, 'Uruburetama', 2302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23011, 'Médio Curu', 2302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23012, 'Canindé', 2302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23013, 'Baturité', 2302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23014, 'Chorozinho', 2302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23015, 'Cascavel', 2302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23016, 'Fortaleza', 2303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23017, 'Pacajus', 2303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23018, 'Sertão de Cratéus', 2304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23019, 'Sertão de Quixeramobim', 2304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23020, 'Sertão de Inhamuns', 2304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23021, 'Sertão de Senador Pompeu', 2304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23022, 'Litoral de Aracati', 2305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23023, 'Baixo Jaguaribe', 2305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23024, 'Médio Jaguaribe', 2305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23025, 'Serra do Pereiro', 2305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23026, 'Iguatu', 2306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23027, 'Várzea Alegre', 2306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23028, 'Lavras da Mangabeira', 2306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23029, 'Chapada do Araripe', 2307);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23030, 'Caririaçu', 2307);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23031, 'Barro', 2307);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23032, 'Cariri', 2307);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 23033, 'Brejo Santo', 2307);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24001, 'Mossoró', 2401);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24002, 'Chapada do Apodi', 2401);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24003, 'Médio Oeste', 2401);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24004, 'Vale do Açu', 2401);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24005, 'Serra de São Miguel', 2401);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24006, 'Pau dos Ferros', 2401);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24007, 'Umarizal', 2401);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24008, 'Macau', 2402);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24009, 'Angicos', 2402);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24010, 'Serra de Santana', 2402);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24011, 'Seridó Ocidental', 2402);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24012, 'Seridó Oriental', 2402);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24013, 'Baixa Verde', 2403);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24014, 'Borborema Potiguar', 2403);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24015, 'Agreste Potiguar', 2403);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24016, 'Litoral Nordeste', 2404);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24017, 'Macaíba', 2404);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24018, 'Natal', 2404);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 24019, 'Litoral Sul', 2404);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25001, 'Catolé do Rocha', 2501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25002, 'Cajazeiras', 2501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25003, 'Sousa', 2501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25004, 'Patos', 2501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25005, 'Piancó', 2501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25006, 'Itaporanga', 2501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25007, 'Serra do Teixeira', 2501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25008, 'Seridó Ocidental Paraibano', 2502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25009, 'Seridó Oriental Paraibano', 2502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25010, 'Cariri Ocidental', 2502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25011, 'Cariri Oriental', 2502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25012, 'Curimataú Ocidental', 2503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25013, 'Curimataú Oriental', 2503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25014, 'Esperança', 2503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25015, 'Brejo Paraibano', 2503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25016, 'Guarabira', 2503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25017, 'Campina Grande', 2503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25018, 'Itabaiana', 2503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25019, 'Umbuzeiro', 2503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25020, 'Litoral Norte', 2504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25021, 'Sapé', 2504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25022, 'João Pessoa', 2504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 25023, 'Litoral Sul', 2504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26001, 'Araripina', 2601);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26002, 'Salgueiro', 2601);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26003, 'Pajeú', 2601);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26004, 'Sertão do Moxotó', 2601);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26005, 'Petrolina', 2602);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26006, 'Itaparica', 2602);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26007, 'Vale do Ipanema', 2603);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26008, 'Vale do Ipojuca', 2603);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26009, 'Alto Capibaribe', 2603);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26010, 'Médio Capibaribe', 2603);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26011, 'Garanhuns', 2603);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26012, 'Brejo Pernambucano', 2603);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26013, 'Mata Setentrional Pernambucana', 2604);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26014, 'Vitória de Santo Antão', 2604);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26015, 'Mata Meridional Pernambucana', 2604);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26016, 'Itamaracá', 2605);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26017, 'Recife', 2605);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26018, 'Suape', 2605);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 26019, 'Fernando de Noronha', 2605);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27001, 'Serrana do Sertão Alagoano', 2701);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27002, 'Alagoana do Sertão do São Francisco', 2701);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27003, 'Santana do Ipanema', 2701);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27004, 'Batalha', 2701);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27005, 'Palmeira dos Índios', 2702);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27006, 'Arapiraca', 2702);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27007, 'Traipu', 2702);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27008, 'Serrana dos Quilombos', 2703);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27009, 'Mata Alagoana', 2703);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27010, 'Litoral Norte Alagoano', 2703);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27011, 'Maceió', 2703);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27012, 'São Miguel dos Campos', 2703);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 27013, 'Penedo', 2703);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28001, 'Sergipana do Sertão do São Francisco', 2801);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28002, 'Carira', 2801);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28003, 'Nossa Senhora das Dores', 2802);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28004, 'Agreste de Itabaiana', 2802);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28005, 'Tobias Barreto', 2802);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28006, 'Agreste de Lagarto', 2802);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28007, 'Propriá', 2803);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28008, 'Cotinguiba', 2803);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28009, 'Japaratuba', 2803);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28010, 'Baixo Cotinguiba', 2803);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28011, 'Aracaju', 2803);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28012, 'Boquim', 2803);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 28013, 'Estância', 2803);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29001, 'Barreiras', 2901);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29002, 'Cotegipe', 2901);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29003, 'Santa Maria da Vitória', 2901);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29004, 'Juazeiro', 2902);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29005, 'Paulo Afonso', 2902);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29006, 'Barra', 2902);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29007, 'Bom Jesus da Lapa', 2902);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29008, 'Senhor do Bonfim', 2903);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29009, 'Irecê', 2903);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29010, 'Jacobina', 2903);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29011, 'Itaberaba', 2903);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29012, 'Feira de Santana', 2903);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29013, 'Jeremoabo', 2904);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29014, 'Euclides da Cunha', 2904);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29015, 'Ribeira do Pombal', 2904);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29016, 'Serrinha', 2904);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29017, 'Alagoinhas', 2904);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29018, 'Entre Rios', 2904);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29019, 'Catu', 2905);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29020, 'Santo Antônio de Jesus', 2905);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29021, 'Salvador', 2905);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29022, 'Boquira', 2906);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29023, 'Seabra', 2906);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29024, 'Jequié', 2906);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29025, 'Livramento do Brumado', 2906);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29026, 'Guanambi', 2906);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29027, 'Brumado', 2906);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29028, 'Vitória da Conquista', 2906);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29029, 'Itapetinga', 2906);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29030, 'Valença', 2907);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29031, 'Ilhéus-Itabuna', 2907);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 29032, 'Porto Seguro', 2907);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31001, 'Unaí', 3101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31002, 'Paracatu', 3101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31003, 'Januária', 3102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31004, 'Janaúba', 3102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31005, 'Salinas', 3102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31006, 'Pirapora', 3102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31007, 'Montes Claros', 3102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31008, 'Grão Mogol', 3102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31009, 'Bocaiúva', 3102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31010, 'Diamantina', 3103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31011, 'Capelinha', 3103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31012, 'Araçuaí', 3103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31013, 'Pedra Azul', 3103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31014, 'Almenara', 3103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31015, 'Teófilo Otoni', 3104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31016, 'Nanuque', 3104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31017, 'Ituiutaba', 3105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31018, 'Uberlândia', 3105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31019, 'Patrocínio', 3105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31020, 'Patos de Minas', 3105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31021, 'Frutal', 3105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31022, 'Uberaba', 3105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31023, 'Araxá', 3105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31024, 'Três Marias', 3106);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31025, 'Curvelo', 3106);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31026, 'Bom Despacho', 3106);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31027, 'Sete Lagoas', 3107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31028, 'Conceição do Mato Dentro', 3107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31029, 'Pará de Minas', 3107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31030, 'Belo Horizonte', 3107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31031, 'Itabira', 3107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31032, 'Itaguara', 3107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31033, 'Ouro Preto', 3107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31034, 'Conselheiro Lafaiete', 3107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31035, 'Guanhães', 3108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31036, 'Peçanha', 3108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31037, 'Governador Valadares', 3108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31038, 'Mantena', 3108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31039, 'Ipatinga', 3108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31040, 'Caratinga', 3108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31041, 'Aimorés', 3108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31042, 'Piuí', 3109);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31043, 'Divinópolis', 3109);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31044, 'Formiga', 3109);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31045, 'Campo Belo', 3109);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31046, 'Oliveira', 3109);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31047, 'Passos', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31048, 'São Sebastião do Paraíso', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31049, 'Alfenas', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31050, 'Varginha', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31051, 'Poços de Caldas', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31052, 'Pouso Alegre', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31053, 'Santa Rita do Sapucaí', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31054, 'São Lourenço', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31055, 'Andrelândia', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31056, 'Itajubá', 3110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31057, 'Lavras', 3111);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31058, 'São João Del Rei', 3111);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31059, 'Barbacena', 3111);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31060, 'Ponte Nova', 3112);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31061, 'Manhuaçu', 3112);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31062, 'Viçosa', 3112);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31063, 'Muriaé', 3112);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31064, 'Ubá', 3112);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31065, 'Juiz de Fora', 3112);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 31066, 'Cataguases', 3112);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32001, 'Barra de São Francisco', 3201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32002, 'Nova Venécia', 3201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32003, 'Colatina', 3201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32004, 'Montanha', 3202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32005, 'São Mateus', 3202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32006, 'Linhares', 3202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32007, 'Afonso Cláudio', 3203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32008, 'Santa Teresa', 3203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32009, 'Vitória', 3203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32010, 'Guarapari', 3203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32011, 'Alegre', 3204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32012, 'Cachoeiro de Itapemirim', 3204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 32013, 'Itapemirim', 3204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33001, 'Itaperuna', 3301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33002, 'Santo Antônio de Pádua', 3301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33003, 'Campos dos Goytacazes', 3302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33004, 'Macaé', 3302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33005, 'Três Rios', 3303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33006, 'Cantagalo-Cordeiro', 3303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33007, 'Nova Friburgo', 3303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33008, 'Santa Maria Madalena', 3303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33009, 'Bacia de São João', 3304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33010, 'Lagos', 3304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33011, 'Vale do Paraíba Fluminense', 3305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33012, 'Barra do Piraí', 3305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33013, 'Baía da Ilha Grande', 3305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33014, 'Vassouras', 3306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33015, 'Serrana', 3306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33016, 'Macacu-Caceribu', 3306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33017, 'Itaguaí', 3306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 33018, 'Rio de Janeiro', 3306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35001, 'Jales', 3501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35002, 'Fernandópolis', 3501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35003, 'Votuporanga', 3501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35004, 'São José do Rio Preto', 3501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35005, 'Catanduva', 3501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35006, 'Auriflama', 3501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35007, 'Nhandeara', 3501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35008, 'Novo Horizonte', 3501);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35009, 'Barretos', 3502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35010, 'São Joaquim da Barra', 3502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35011, 'Ituverava', 3502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35012, 'Franca', 3502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35013, 'Jaboticabal', 3502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35014, 'Ribeirão Preto', 3502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35015, 'Batatais', 3502);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35016, 'Andradina', 3503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35017, 'Araçatuba', 3503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35018, 'Birigui', 3503);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35019, 'Lins', 3504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35020, 'Bauru', 3504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35021, 'Jaú', 3504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35022, 'Avaré', 3504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35023, 'Botucatu', 3504);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35024, 'Araraquara', 3505);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35025, 'São Carlos', 3505);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35026, 'Rio Claro', 3506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35027, 'Limeira', 3506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35028, 'Piracicaba', 3506);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35029, 'Pirassununga', 3507);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35030, 'São João da Boa Vista', 3507);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35031, 'Mogi Mirim', 3507);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35032, 'Campinas', 3507);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35033, 'Amparo', 3507);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35034, 'Dracena', 3508);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35035, 'Adamantina', 3508);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35036, 'Presidente Prudente', 3508);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35037, 'Tupã', 3509);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35038, 'Marília', 3509);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35039, 'Assis', 3510);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35040, 'Ourinhos', 3510);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35041, 'Itapeva', 3511);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35042, 'Itapetininga', 3511);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35043, 'Tatuí', 3511);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35044, 'Capão Bonito', 3511);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35045, 'Piedade', 3512);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35046, 'Sorocaba', 3512);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35047, 'Jundiaí', 3512);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35048, 'Bragança Paulista', 3512);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35049, 'Campos do Jordão', 3513);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35050, 'São José dos Campos', 3513);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35051, 'Guaratinguetá', 3513);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35052, 'Bananal', 3513);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35053, 'Paraibuna/Paraitinga', 3513);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35054, 'Caraguatatuba', 3513);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35055, 'Registro', 3514);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35056, 'Itanhaém', 3514);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35057, 'Osasco', 3515);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35058, 'Franco da Rocha', 3515);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35059, 'Guarulhos', 3515);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35060, 'Itapecerica da Serra', 3515);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35061, 'São Paulo', 3515);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35062, 'Mogi das Cruzes', 3515);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 35063, 'Santos', 3515);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41001, 'Paranavaí', 4101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41002, 'Umuarama', 4101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41003, 'Cianorte', 4101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41004, 'Goioerê', 4102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41005, 'Campo Mourão', 4102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41006, 'Astorga', 4103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41007, 'Porecatu', 4103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41008, 'Floraí', 4103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41009, 'Maringá', 4103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41010, 'Apucarana', 4103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41011, 'Londrina', 4103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41012, 'Faxinal', 4103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41013, 'Ivaiporã', 4103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41014, 'Assaí', 4104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41015, 'Cornélio Procópio', 4104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41016, 'Jacarezinho', 4104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41017, 'Ibaiti', 4104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41018, 'Wenceslau Braz', 4104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41019, 'Telêmaco Borba', 4105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41020, 'Jaguariaíva', 4105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41021, 'Ponta Grossa', 4105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41022, 'Toledo', 4106);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41023, 'Cascavel', 4106);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41024, 'Foz do Iguaçu', 4106);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41025, 'Capanema', 4107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41026, 'Francisco Beltrão', 4107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41027, 'Pato Branco', 4107);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41028, 'Pitanga', 4108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41029, 'Guarapuava', 4108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41030, 'Palmas', 4108);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41031, 'Prudentópolis', 4109);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41032, 'Irati', 4109);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41033, 'União da Vitória', 4109);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41034, 'São Mateus do Sul', 4109);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41035, 'Cerro Azul', 4110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41036, 'Lapa', 4110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41037, 'Curitiba', 4110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41038, 'Paranaguá', 4110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 41039, 'Rio Negro', 4110);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42001, 'São Miguel do Oeste', 4201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42002, 'Chapecó', 4201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42003, 'Xanxerê', 4201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42004, 'Joaçaba', 4201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42005, 'Concórdia', 4201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42006, 'Canoinhas', 4202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42007, 'São Bento do Sul', 4202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42008, 'Joinville', 4202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42009, 'Curitibanos', 4203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42010, 'Campos de Lages', 4203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42011, 'Rio do Sul', 4204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42012, 'Blumenau', 4204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42013, 'Itajaí', 4204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42014, 'Ituporanga', 4204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42015, 'Tijucas', 4205);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42016, 'Florianópolis', 4205);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42017, 'Tabuleiro', 4205);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42018, 'Tubarão', 4206);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42019, 'Criciúma', 4206);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 42020, 'Araranguá', 4206);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43001, 'Santa Rosa', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43002, 'Três Passos', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43003, 'Frederico Westphalen', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43004, 'Erechim', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43005, 'Sananduva', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43006, 'Cerro Largo', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43007, 'Santo Ângelo', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43008, 'Ijuí', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43009, 'Carazinho', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43010, 'Passo Fundo', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43011, 'Cruz Alta', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43012, 'Não-Me-Toque', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43013, 'Soledade', 4301);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43014, 'Guaporé', 4302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43015, 'Vacaria', 4302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43016, 'Caxias do Sul', 4302);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43017, 'Santiago', 4303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43018, 'Santa Maria', 4303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43019, 'Restinga Seca', 4303);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43020, 'Santa Cruz do Sul', 4304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43021, 'Lajeado-Estrela', 4304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43022, 'Cachoeira do Sul', 4304);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43023, 'Montenegro', 4305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43024, 'Gramado-Canela', 4305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43025, 'São Jerônimo', 4305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43026, 'Porto Alegre', 4305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43027, 'Osório', 4305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43028, 'Camaquã', 4305);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43029, 'Campanha Ocidental', 4306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43030, 'Campanha Central', 4306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43031, 'Campanha Meridional', 4306);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43032, 'Serras de Sudeste', 4307);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43033, 'Pelotas', 4307);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43034, 'Jaguarão', 4307);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 43035, 'Litoral Lagunar', 4307);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50001, 'Baixo Pantanal', 5001);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50002, 'Aquidauana', 5001);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50003, 'Alto Taquari', 5002);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50004, 'Campo Grande', 5002);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50005, 'Cassilândia', 5003);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50006, 'Paranaíba', 5003);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50007, 'Três Lagoas', 5003);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50008, 'Nova Andradina', 5003);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50009, 'Bodoquena', 5004);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50010, 'Dourados', 5004);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 50011, 'Iguatemi', 5004);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51001, 'Aripuanã', 5101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51002, 'Alta Floresta', 5101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51003, 'Colíder', 5101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51004, 'Parecis', 5101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51005, 'Arinos', 5101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51006, 'Alto Teles Pires', 5101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51007, 'Sinop', 5101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51008, 'Paranatinga', 5101);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51009, 'Norte Araguaia', 5102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51010, 'Canarana', 5102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51011, 'Médio Araguaia', 5102);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51012, 'Alto Guaporé', 5103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51013, 'Tangará da Serra', 5103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51014, 'Jauru', 5103);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51015, 'Alto Paraguai', 5104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51016, 'Rosário Oeste', 5104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51017, 'Cuiabá', 5104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51018, 'Alto Pantanal', 5104);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51019, 'Primavera do Leste', 5105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51020, 'Tesouro', 5105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51021, 'Rondonópolis', 5105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 51022, 'Alto Araguaia', 5105);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52001, 'São Miguel do Araguaia', 5201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52002, 'Rio Vermelho', 5201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52003, 'Aragarças', 5201);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52004, 'Porangatu', 5202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52005, 'Chapada dos Veadeiros', 5202);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52006, 'Ceres', 5203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52007, 'Anápolis', 5203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52008, 'Iporá', 5203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52009, 'Anicuns', 5203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52010, 'Goiânia', 5203);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52011, 'Vão do Paranã', 5204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52012, 'Entorno de Brasília', 5204);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52013, 'Sudoeste de Goiás', 5205);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52014, 'Vale do Rio dos Bois', 5205);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52015, 'Meia Ponte', 5205);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52016, 'Pires do Rio', 5205);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52017, 'Catalão', 5205);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 52018, 'Quirinópolis', 5205);
insert into microrregiao (idmicrorregiao, nome, idmesorregiao) values ( 53001, 'Brasília', 5301);
